version: '3.8'

services:
  # db:
  #   image: postgres:15
  #   container_name: wristcheck_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: wristcheck_db
  #   ports:
  #     - "127.0.0.1:5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: catalog_server
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: ${PORT}
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
