version: '3.8'

services:
  app:
    build: .
    container_name: catalog_server
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PORT: ${PORT}
    ports:
      - "3000:3000"

volumes:
  db_data:

