name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Build and Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            git config --global --add safe.directory /var/www/production/catalog
            cd /var/www/production/catalog || exit 1
            git pull origin master || exit 1
            docker compose -f docker-compose.prod.yml pull || exit 1
            docker compose -f docker-compose.prod.yml build || exit 1
            docker compose -f docker-compose.prod.yml up -d || exit 1
          EOF
